# Generated by Django 3.2.5 on 2021-12-11 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_producto', models.CharField(max_length=50)),
                ('precio_producto', models.FloatField()),
                ('descripcion_producto', models.CharField(max_length=100)),
                ('cantidad_existencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_proveedor', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.FloatField()),
                ('nom_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.articulos')),
            ],
        ),
        migrations.CreateModel(
            name='PE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.FloatField()),
                ('nom_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.articulos')),
            ],
        ),
    ]
