# Generated by Django 3.2.5 on 2021-12-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_producto', models.CharField(max_length=50)),
                ('precio_producto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Postres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_postre', models.CharField(max_length=100)),
                ('tipo_postre', models.CharField(max_length=100)),
                ('nom_postre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menú.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_platillo', models.CharField(max_length=100)),
                ('tipo_comida', models.CharField(max_length=100)),
                ('nom_platillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menú.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CafePreparado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_cafe', models.CharField(max_length=100)),
                ('tipo_cafe', models.CharField(max_length=100)),
                ('nom_cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menú.producto')),
            ],
        ),
        migrations.CreateModel(
            name='CafeGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_CafeGranel', models.CharField(max_length=100)),
                ('tipo_CafeGranel', models.CharField(max_length=100)),
                ('nom_CafeGranel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menú.producto')),
            ],
        ),
    ]
